In [10]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import linear_model
import matplotlib 


In [12]:
df = pd.read_csv("winequality-red.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [13]:
df=df.drop(['chlorides','free sulfur dioxide','total sulfur dioxide','density','sulphates','fixed acidity','volatile acidity','citric acid',],axis='columns')
df

residual sugar    pH  alcohol  quality
0                1.9  3.51      9.4        5
1                2.6  3.20      9.8        5
2                2.3  3.26      9.8        5
3                1.9  3.16      9.8        6
4                1.9  3.51      9.4        5
...              ...   ...      ...      ...
1594             2.0  3.45     10.5        5
1595             2.2  3.52     11.2        6
1596             2.3  3.42     11.0        6
1597             2.0  3.57     10.2        5
1598             3.6  3.39     11.0        6

[1599 rows x 4 columns]

In [14]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('quality',axis='columns'),df.quality)
df

residual sugar    pH  alcohol  quality
0                1.9  3.51      9.4        5
1                2.6  3.20      9.8        5
2                2.3  3.26      9.8        5
3                1.9  3.16      9.8        6
4                1.9  3.51      9.4        5
...              ...   ...      ...      ...
1594             2.0  3.45     10.5        5
1595             2.2  3.52     11.2        6
1596             2.3  3.42     11.0        6
1597             2.0  3.57     10.2        5
1598             3.6  3.39     11.0        6

[1599 rows x 4 columns]

In [17]:
reg.predict([[1.9,3.51,9.4]])

array([5.07661025])

In [18]:
X=df[['residual sugar','pH','alcohol']]

In [19]:
y=df['quality']

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2) 

In [21]:
X_train


residual sugar    pH  alcohol
376             3.0  3.26     11.0
835             1.5  3.39      9.3
812             2.5  3.24     10.8
154             5.5  3.42     10.5
93              1.9  3.39      9.6
..              ...   ...      ...
37              2.1  3.23      9.7
525             2.8  3.24      9.9
869             2.0  3.44     10.9
615             2.3  3.50      9.7
890             2.0  3.44     10.1

[1279 rows x 3 columns]

In [23]:
X_test

residual sugar    pH  alcohol
873            1.60  3.23     11.1
291            2.00  3.30     10.5
829            2.10  3.56     11.1
838            1.60  3.24     11.2
139            2.00  3.32      9.5
..              ...   ...      ...
691            2.60  3.48      9.8
982            2.10  3.34     12.9
915            2.20  3.27     11.9
462            2.55  3.18     11.8
53             3.00  3.20      9.4

[320 rows x 3 columns]

In [24]:
y_train


376    6
835    5
812    5
154    5
93     5
      ..
37     7
525    5
869    6
615    5
890    5
Name: quality, Length: 1279, dtype: int64

In [25]:
y_test

873    7
291    5
829    6
838    7
139    5
      ..
691    5
982    6
915    6
462    5
53     5
Name: quality, Length: 320, dtype: int64

In [26]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
clf.predict(X_test)

array([5.97120983, 5.66895098, 5.66432575, 6.00116697, 5.25923824,
       4.99497629, 5.93776615, 5.30517977, 5.64899599, 5.05486592,
       5.79936237, 5.99717173, 5.68679919, 6.22685131, 5.28677359,
       5.54125173, 5.65897349, 5.18501159, 5.79795797, 5.7734744 ,
       5.31789405, 5.87334795, 5.29675108, 5.26432632, 5.59990755,
       5.25892324, 5.3759233 , 5.38015618, 5.79793333, 5.37536189,
       5.39529225, 5.74644775, 6.16967382, 5.39698891, 5.97123447,
       5.34535547, 5.2573005 , 5.51478458, 5.24354763, 5.9763684 ,
       5.6408823 , 5.18346278, 5.23124348, 5.90461282, 6.34667985,
       5.32973536, 5.59361029, 5.93212353, 5.31832882, 5.51478458,
       5.97154947, 5.51725222, 5.59029776, 5.69144906, 6.26986236,
       5.87463105, 6.02524041, 5.39337915, 5.418227  , 5.41825164,
       6.30081224, 5.67461824, 6.23496652, 5.33511226, 5.31917715,
       5.5286834 , 5.35175129, 5.18501159, 6.33151914, 5.52749543,
       6.12855809, 6.11353836, 5.15832457, 5.70221689, 5.22368

In [29]:
y_test

873    7
291    5
829    6
838    7
139    5
      ..
691    5
982    6
915    6
462    5
53     5
Name: quality, Length: 320, dtype: int64

In [30]:
clf.score(X_test, y_test)

0.2310561489370293

In [31]:
import pickle

In [32]:
with open('model_pickle','wb') as file:
    pickle.dump(reg,file)

In [33]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [34]:
mp.coef_

array([-0.01252732, -0.8613732 ,  0.38719996])

In [35]:
mp.intercept_

4.484152506269748

In [36]:
mp.predict([[2.5,5,15]])

array([5.95396755])

In [37]:
mp.predict([[5.6,8,24]])

array([6.81581286])